name: Build and Release Kotlin APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Позволяет запускать билд вручную из вкладки Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Скачиваем исходный код репозитория
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Настраиваем Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      # 3. Даем права на запуск Gradle в среде Linux
      - name: Grant Execute Permission for Gradle
        run: chmod +x ./gradlew

      # Извлекаем чистую версию из тега и считаем коммиты
      - name: Parse Version From Tag
        id: parse_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            TAG_NAME="${{ github.ref_name }}"
          else
            TAG_NAME="v0.0.0-manual"
          fi
          VERSION=${TAG_NAME#v} 
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV
          
          COMMITS_COUNT=$(git rev-list --count HEAD)
          echo "VERSION_CODE=$COMMITS_COUNT" >> $GITHUB_ENV

      # 4. Собираем RELEASE APK
      - name: Build Release APK
        run: |
          ./gradlew app:assembleRelease \
            -PVERSION_CODE=${{ env.VERSION_CODE }} \
            -PVERSION_NAME="${{ env.VERSION_NAME }}"

      # 5. Сохраняем готовый файл в Releases
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/*.apk
          name: Release ${{ env.VERSION_NAME }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
